### ISSUE TITLE
Distinction from simfinR

### ISSUE THREAD

**Issue by GitHubGeniusOverlord** [matthiasgomolka/simfinapi#22]
Hi,

I was wondering whether you could leave a short note in the documentary about the distinction to the library "simfinR". What to expect from this one and why you chose to make it. 
This can be a crucial information for anyone trying to decide which package to choose. (Thats why its an issue)

Danke!
Thank You.

**Comment by matthiasgomolka** [comment]
Hi, and thanks for the suggenstion. 

To be honest, I don't recall all the details any more. I think, when I started working on `simfinapi`, `simfinR` was not on CRAN yet and I was planning to use SimFin data in a personal project I wanted to run for a couple of years. Thus, I wrapped the SimFin API myself.

From a quick glance over the simfinR codebase, I see the following differences between `simfinapi` and `simfinR` right now:

- `simfinapi` leverages `v2` of the SimFin Web API which was released last summer whereas `simfinR` uses `v1`. `v2` of the Web API greatly improves the structure of response so that the result is easier to use. It also allows for more comprehensive queries if you are a SimFin+ user. 
- `simfinapi` should be faster because it
  - queries the API in parallel if you specify a `future::plan()`,
  - uses [RcppSimdJson](https://CRAN.R-project.org/package=RcppSimdJson) instead of [jsonlite](https://CRAN.R-project.org/package=jsonlite) to parse the JSON response from the API,
  - uses [data.table](https://CRAN.R-project.org/package=data.table) instead of [dplyr](https://CRAN.R-project.org/package=dplyr) for internal data manipulation
- `simfinapi` is potentially more reliable because it
  - includes a range of tests on a range of different R versions and platforms
  - it uses [httr](https://CRAN.R-project.org/package=httr) to handle all API returns safely
- `simfinapi` might be more convenient to use because it includes functions to set the API key and the caching directory so that you don't have to pass these to each function call

@msperlin, please feel free to comment if I overlooked something in `simfinR`.

**Comment by msperlin** [comment]
Hi @matthiasgomolka,

Looks great, specially the use of the v2 api. 
The more options, the better. 

Best,

**Comment by matthiasgomolka** [comment]
@GitHubGeniusOverlord, I added a small section at the end of the [GitHub README](https://github.com/matthiasgomolka/simfinapi#relation-to-simfinr) linking to this issue. I guess, this addresses your initial question? If not, please reopen this issue and elaborate.

**Comment by GitHubGeniusOverlord** [comment]
Hi @matthiasgomolka Thanks for elaborating! And thanks for the awesome package. If you ever feel like you cant maintain it, I would take some time.
